### ISSUE TITLE
Background color

### ISSUE THREAD

**Issue by frjariello** [nswamy14/visual-heatmap#29] opened 2024-05-27 07:01 UTC
Hi, 
I'm trying different heatmap scripts, and at the moment I think yours is the most performing and realistic, the only thing, in my case, I would have to 'fill' the whole canvas with a base color (semi-transparent green), so how could I attribute a color to the remaining areas, those without mapping, currently transparent?
Thank you

**Comment by nswamy14** [comment] 2024-05-30 03:29
@frjariello , the current implementation allows you to set background images through the API. Alternatively, you can set the background color directly on the container Div element if that suits your needs.

I am planning to introduce new layers—background and overlay layers—in addition to the existing heatmap layer. This will enable full support for shapes, text, and colors as both background and overlay elements on the heatmap layer.

**Comment by nswamy14** [comment] 2024-06-23 03:09
Closing this issue as it is not a bug.

**Closed as completed by nswamy14** 2024-06-23 03:09 UTC
